# 端口号配置
server:
  port: 8089

# 数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: LYP1314521

# 微信小程序相关
Wechat:
  Applets:
    # 小程序appID
    appId: wxc2f9f05e369786ff
    # 小程序秘钥
    appSecret: ddaef6972a0e91f1ffa9a90a3c6fb6e6


#图片上传
web:
  uploadpath: D:/BISHE/images/  #图片上传的路径
  loadpath: file:D:/BISHE/images/ #图片访问、加载的路径

# Mybatis Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置 Mybatis Plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'
